config/routes.rb
Rails.application.routes.draw do
  devise_for :users,controllers: {
    registrations: 'users/registrations',
    omniauth_callbacks: "users/omniauth_callbacks"
  } 
  devise_scope :user do
      get 'personal_name_google' => 'users/registrations#personal_name_google'
      get 'phone_number_google' => 'users/registrations#phone_number_google'
      get 'personal_name' => 'users/registrations#personal_name'
      get 'phone_number' => 'users/registrations#phone_number'
      get 'address' => 'users/registrations#address'
      get 'creditcard' => 'users/registrations#creditcard'
  end
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :joint,only:[:index]
  root to: 'joint#index'

  # マイページ
  resource :mypage, only:[:show] do
    member do
      # ログアウト画面の表示
      get :logout
    end
    scope module: :mypage do
      namespace :sale do
        resources :selling, only: [:index]
        resources :dealing, only: [:index]
        resources :closed, only: [:index]
      end
      namespace :purchase do
        resources :dealing, only: [:index]
        resources :closed, only: [:index]
      end
      resource :profiles, only:[:new, :create, :edit, :update]
      resource :personals, only:[:edit, :update]
      resources :mypage_payjp_cards, only:[:index, :new, :create, :destroy], path: "cards", as: :cards
    end
  end

  resources :users, only:[:show]

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?


  resources :items do

    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
      get 'get_deliver_method', defaults: { format: 'json' }
      get 'get_deliver_method_cash_on_delivery', defaults: { format: 'json' }
    end

    member do
      # 商品販売状態の変更
      patch :deactivate
      patch :activate
    end

    # 商品購入ページ
    scope module: :deals do
      resources :purchase, only: [:new, :create], path: 'transaction'
      resources :deals_payjp_cards, only: [:index, :new, :create], path: "transaction/cards", as: :purchase_card
      resources :deals_delivery_addresses, only: [:new, :create, :edit, :update], path: "transaction/delivery_addresses", as: :purchase_delivery_addresses
    end
  end

  namespace :api do
    resources :brands, only: [] do
      collection do
        # ブランドインクリメンタルサーチ
        get 'search', defaults: { format: 'json' }
      end
    end
  end
end

app/controllers/joint_controller.rb
class JointController < ApplicationController

  def index
    # 人気カテゴリー直近１０アイテムの情報を取得
    @category_datas = []
    category_names = ["レディース","メンズ","家電・スマホ・カメラ","おもちゃ・ホビー・グッズ"]
    category_names.each do |category_name|
      category = Category.find_by(name: category_name)
      subtree_ids = category.subtree_ids
      # 上記親カテゴリ配下のカテゴリに属する販売中の商品の内、直近で出品された10件を取得
      category_items = Item.includes([:item_images]).where(category_id: subtree_ids, sales_state_id: 1).recent(10)
      @category_datas << {category: category, items: category_items}
    end

    # 人気ブランド直近１０アイテムの情報を取得
    @brand_datas = []
    brand_names = ["シャネル","ルイ ヴィトン","シュプリーム","ナイキ"]
    brand_names.each do |brand_name|
      brand = Brand.find_by(name: brand_name)
      # 上記ブランドに属する販売中の商品の内、直近で出品された10件を取得
      brand_items = Item.includes([:item_images]).where(brand: brand, sales_state_id: 1).recent(10)
      @brand_datas << {brand: brand, items: brand_items}
    end

  end
end

app/helpers/joint_helper.rb
module JointHelper
end

app/views/joint/_app__dl.html.haml
.root-app__dl
  .root-app__dl__box
    .root-app__dl__box__left
      .root-app__dl__box__left--title
        スマホでかんたんアプリ
      .root-app__dl__box__left--text
        今すぐ無料ダウンロード
      .root-app__dl__box__left--image
        .root-app__dl__box__left--image--icon
          =image_tag "mercari_icon.png",size: "68x68",class:"root-app__dl__box__left--image--icon--image"
        .root-app__dl__box__left--image--appstore
          =image_tag "app_store.svg",size:"144x40"
        .root-app__dl__box__left--image--googleplay
          =image_tag "google-play.svg",size:"144x40"
    .root-app__dl__box__right
      =image_tag "app_koukoku.png",size:"300x260"

app/views/joint/_exhibit__button.html.haml
.root-exhibit__button
  =link_to new_item_path ,class: "root-exhibit__button", data: {"turbolinks": false} do
    .root-exhibit__button--text
      出品
      = fa_icon "camera 3x", class: "root-exhibit__button__icon"

app/views/joint/_footer.html.haml
%footer.root-footer__menu
  .root-footer__menu__nav
    .root-footer__menu__nav__list
      %h2.root-footer__menu__nav__list--icon
        メルカリについて
      %ul.root-footer__menu__nav__list--outline
        %li.root-footer__menu__nav__list--outline--entity
          =link_to "", class: "root-footer__menu__nav__list--outline--entity" do
            会社概要（運営会社）
        %li.root-footer__menu__nav__list--outline--entity
          =link_to "", class: "root-footer__menu__nav__list--outline--entity" do
            採用情報
        %li.root-footer__menu__nav__list--outline--entity
          =link_to "", class: "root-footer__menu__nav__list--outline--entity" do
            プレスリリース
        %li.root-footer__menu__nav__list--outline--entity
          =link_to "", class: "root-footer__menu__nav__list--outline--entity" do
            公式ブログ
        %li.root-footer__menu__nav__list--outline--entity
          =link_to "", class: "root-footer__menu__nav__list--outline--entity" do
            メルカリロゴ利用ガイドライン
        .root-footer__menu--icon
          = fa_icon "twitter 3x", class: "footer__menu__box__lower--search--category--icon"
          = fa_icon "facebook-square 3x", class: "footer__menu__box__lower--search--category--icon"
    .root-footer__menu__nav__list
      %h2.root-footer__menu__nav__list--icon
        ヘルプ&ガイド
      %ul.root-footer__menu__nav__list--outline
        %li.root-footer__menu__nav__list--outline--entity
          =link_to "", class: "root-footer__menu__nav__list--outline--entity" do
            メルカリガイド
        %li.root-footer__menu__nav__list--outline--entity
          =link_to "", class: "root-footer__menu__nav__list--outline--entity" do
            らくらくメルカリ便
        %li.root-footer__menu__nav__list--outline--entity
          =link_to "", class: "root-footer__menu__nav__list--outline--entity" do
            ゆうゆうメルカリ便
        %li.root-footer__menu__nav__list--outline--entity
          =link_to "", class: "root-footer__menu__nav__list--outline--entity" do
            大型メルカリ便
        %li.root-footer__menu__nav__list--outline--entity
          =link_to "", class: "root-footer__menu__nav__list--outline--entity" do
            車体取引ガイド
        %li.root-footer__menu__nav__list--outline--entity
          =link_to "", class: "root-footer__menu__nav__list--outline--entity" do
            メルカリあんしん・安全宣言
        %li.root-footer__menu__nav__list--outline--entity
          =link_to "", class: "root-footer__menu__nav__list--outline--entity" do
            偽ブランド品撲滅への取り組み
        %li.root-footer__menu__nav__list--outline--entity
          =link_to "", class: "root-footer__menu__nav__list--outline--entity" do
            メルカリボックス
    .root-footer__menu__nav--base
      %h2.root-footer__menu__nav--base--icon
        プライバシーと利用規約
      .root-footer__menu__nav--base--rule
        %ul.root-footer__menu__nav--base--rule__list
          %li.root-footer__menu__nav--base--rule__list--entity
            =link_to "", class: "root-footer__menu__nav--base--rule__list--entity" do
              プライバシーポリシー
          %li.root-footer__menu__nav--base--rule__list--entity
            =link_to "", class: "root-footer__menu__nav--base--rule__list--entity" do
              メルカリ利用規約  
          %li.root-footer__menu__nav--base--rule__list--entity
            =link_to "", class: "root-footer__menu__nav--base--rule__list--entity" do
              あんしんスマホサポート制度に<br>関する利用規約
          %li.root-footer__menu__nav--base--rule__list--entity
            =link_to "", class: "root-footer__menu__nav--base--rule__list--entity" do
              コンプライアンスポリシー
      .root-footer__menu__nav--base--rule
        %ul.root-footer__menu__nav--base--rule__list
          %li.root-footer__menu__nav--base--rule__list--entity
            =link_to "", class: "root-footer__menu__nav--base--rule__list--entity" do
              個人データの安全管理に係る基本方針
          %li.root-footer__menu__nav--base--rule__list--entity
            =link_to "", class: "root-footer__menu__nav--base--rule__list--entity" do
              特定商取引に関する表記
          %li.root-footer__menu__nav--base--rule__list--entity
            =link_to "", class: "root-footer__menu__nav--base--rule__list--entity" do
              資金決済法に基づく表示
          %li.root-footer__menu__nav--base--rule__list--entity
            =link_to "", class: "root-footer__menu__nav--base--rule__list--entity" do
              法令順守と犯罪抑止のために
    .root-footer__menu__nav__list
      %h2.root-footer__menu__nav__list--icon
        国
      %ul.root-footer__menu__nav__list--outline
        %li.root-footer__menu__nav__list--outline--entity
          =link_to "", class: "root-footer__menu__nav__list--outline--entity" do
            日本
        %li.root-footer__menu__nav__list--outline--entity
          =link_to "", class: "root-footer__menu__nav__list--outline--entity" do
            united states
  .root-footer__menu__copyright
    .root-footer__menu__copyright__box
      = link_to root_path do
        =image_tag  "https://web-jp-assets.mercdn.net/_next/static/images/logo-white-1a0696cf557ee1ed6f3c3444661d21ad.svg"
      %span.root-footer__menu__copyright__box--logo
        © 2019 Mercari

app/views/joint/_header.html.haml
%header.root-menu
  .root-menu__box
    .root-menu__box__upper
      .root-menu__box__upper__icon
        = link_to root_path do
          = image_tag "logo-acdd90ac4f472d5a6f7a330d33ab1225.svg", size: "134x36"
      .root-menu__box__upper__form
        %input.root-menu__box__upper--text{placeholder: "何かお探しですか？"}
        %button.root-menu__box__upper--button
          = fa_icon "search", class: "root-menu__box__upper__button"
    .root-menu__box__lower
      .root-menu__box__lower__left
        .root-menu__box__lower__left--category
          =link_to "" ,class: "root-menu__box__lower__left--category" do
            = fa_icon "list-ul", class: "root-menu__box__lower__left--category__icon"
            カテゴリーから探す
        .root-menu__box__lower__left--brand
          =link_to "" ,class: "root-menu__box__lower__left--brand" do
            = fa_icon "tag", class: "root-menu__box__lower__left--category__icon"
            ブランドから探す
      .root-menu__box__lower__right
        - if user_signed_in?
          = link_to mypage_path, class: "root-menu__box__lower__right__mypage" do
            = image_tag 'user/user_photo_noimage.png', height: '32', width: '32', align: "middle", class: 'root-menu__box__lower__right__mypage__avator'
            .root-menu__box__lower__right__mypage__text
              マイページ
        - else
          =link_to new_user_registration_path,class: "root-menu__box__lower__right--sign-in" do
            新規会員登録
          =link_to new_user_session_path,class: "root-menu__box__lower__right--log-in" do
            ログイン

  .root-short-menu
    .root-short-menu__box
      .root-short-menu__box__upper
        .root-short-menu__box__upper--left
          = image_tag "logo-acdd90ac4f472d5a6f7a330d33ab1225.svg", size: "134x36"
        .root-short-menu__box__upper__right
          - if user_signed_in?
            = link_to mypage_path, class: "root-menu__box__lower__right__mypage" do
              = image_tag 'user/user_photo_noimage.png', height: '32', width: '32', align: "middle", class: 'root-menu__box__lower__right__mypage__avator'
          - else
            =link_to new_user_registration_path,class: "root-short-menu__box__upper__right--sign-in" do
              新規会員登録
            =link_to new_user_session_path,class: "root-short-menu__box__upper__right--log-in" do
              ログイン
      .root-short-menu__box__center
        %input.root-short-menu__box__center--text
        .root-short-menu__box__upper--button
          = fa_icon "search", class: "root-short-menu__box__upper__button__icon"
      .root-short-menu__box__lower
        =link_to "", class: "root-short-menu__box__lower--category" do
          = fa_icon "list-ul", class: "root-menu__box__lower__left--category__icon"
          カテゴリーから探す
        =link_to "", class: "root-short-menu__box__lower--brand" do
          = fa_icon "tag", class: "root-menu__box__lower__left--category__icon"
          ブランドから探す

app/views/joint/_itembox.html.haml
.root-new__production
  .root-new__production__box{data: {category_id: category.id }}
    .root-new__production__box__upper
      .root-new__production__box__upper--name
        #{category.name}新着アイテム
      .root-new__production__box__upper--detail-path
        =link_to "もっと見る","",class:"root-new__production__box__upper--detail-path"
    .root-new__production__box__group
      .root-new__production__box__group__list
        - items.each do |item|
          =link_to item_path(item), class:"root-new__production__box__group__list__box" do
            .root-new__production__box__group__list__imagebox
              - unless item.item_images.empty?
                = image_tag item.item_images.first.image.url, class: "root-new__production__box__group__list__imagebox--image"
              - else
                = image_tag "no_image.png", class: "root-new__production__box__group__list__imagebox--image"
              .root-new__production__box__group__list--price
                %span.root-new__production__box__group__list--price--span
                  = item.decorate.amount_text
            .root-new__production__box__group__list--text
              %span.root-new__production__box__group__list--text--span
                = item.name

app/views/joint/_itembox_brand.html.haml
.root-new__production
  .root-new__production__box{data: {brand_id: brand.id }}
    .root-new__production__box__upper
      .root-new__production__box__upper--name
        #{brand.name}新着アイテム
      .root-new__production__box__upper--detail-path
        =link_to "もっと見る","",class:"root-new__production__box__upper--detail-path"
    .root-new__production__box__group
      .root-new__production__box__group__list
        - items.each do |item|
          =link_to item_path(item), class:"root-new__production__box__group__list__box" do
            .root-new__production__box__group__list__imagebox
              - unless item.item_images.empty?
                = image_tag item.item_images.first.image.url, class: "root-new__production__box__group__list__imagebox--image"
              - else
                = image_tag "no_image.png", class: "root-new__production__box__group__list__imagebox--image"
              .root-new__production__box__group__list--price
                %span.root-new__production__box__group__list--price--span
                  = item.decorate.amount_text  
            .root-new__production__box__group__list--text
              %span.root-new__production__box__group__list--text--span
                = item.name

app/views/joint/index.html.haml
.root-wrapper
  = render partial: 'header'
  .root-contents
    .root-campaign
      .root-campaign__arrow__left
      .root-campaign__arrow__right
      .root-campaign__slider
        %span.root-campaign__slider1
        %span.root-campaign__slider2
    -# 人気のカテゴリー表示
    .root-category__box
      .root-category__box--popular
        人気のカテゴリー
      %ul.root-category__box__list
        - @category_datas.each do |category_data|
          %li.root-category__box__list--label.popular_category_label{data: {category_id: category_data[:category].id }}
            = category_data[:category].name
    -# 表示するカテゴリーの数だけ繰り返し処理
    - @category_datas.each do |category_data|
      = render partial: 'itembox', locals: { category: category_data[:category], items: category_data[:items] }
    -# 人気のブランドー表示
    .root-category__box
      .root-category__box--popular
        人気のブランド
      %ul.root-category__box__list
        - @brand_datas.each do |brand_data|
          %li.root-category__box__list--label.popular_brand_label{ data: {brand_id: brand_data[:brand].id }}
            = brand_data[:brand].name
    -# 表示するブランドの数だけ繰り返し処理
    - @brand_datas.each do |brand_data|
      = render partial: 'itembox_brand', locals: { brand: brand_data[:brand], items: brand_data[:items] }
  = render partial: 'app__dl'
  = render partial: 'footer'
  = render partial: 'exhibit__button'