config/routes.rb
Rails.application.routes.draw do
  devise_for :users,controllers: {
    registrations: 'users/registrations',
    omniauth_callbacks: "users/omniauth_callbacks"
  } 
  devise_scope :user do
      get 'personal_name_google' => 'users/registrations#personal_name_google'
      get 'phone_number_google' => 'users/registrations#phone_number_google'
      get 'personal_name' => 'users/registrations#personal_name'
      get 'phone_number' => 'users/registrations#phone_number'
      get 'address' => 'users/registrations#address'
      get 'creditcard' => 'users/registrations#creditcard'
  end
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :joint,only:[:index]
  root to: 'joint#index'

  # マイページ
  resource :mypage, only:[:show] do
    member do
      # ログアウト画面の表示
      get :logout
    end
    scope module: :mypage do
      namespace :sale do
        resources :selling, only: [:index]
        resources :dealing, only: [:index]
        resources :closed, only: [:index]
      end
      namespace :purchase do
        resources :dealing, only: [:index]
        resources :closed, only: [:index]
      end
      resource :profiles, only:[:new, :create, :edit, :update]
      resource :personals, only:[:edit, :update]
      resources :mypage_payjp_cards, only:[:index, :new, :create, :destroy], path: "cards", as: :cards
    end
  end

  resources :users, only:[:show]

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?


  resources :items do

    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
      get 'get_deliver_method', defaults: { format: 'json' }
      get 'get_deliver_method_cash_on_delivery', defaults: { format: 'json' }
    end

    member do
      # 商品販売状態の変更
      patch :deactivate
      patch :activate
    end

    # 商品購入ページ
    scope module: :deals do
      resources :purchase, only: [:new, :create], path: 'transaction'
      resources :deals_payjp_cards, only: [:index, :new, :create], path: "transaction/cards", as: :purchase_card
      resources :deals_delivery_addresses, only: [:new, :create, :edit, :update], path: "transaction/delivery_addresses", as: :purchase_delivery_addresses
    end
  end

  namespace :api do
    resources :brands, only: [] do
      collection do
        # ブランドインクリメンタルサーチ
        get 'search', defaults: { format: 'json' }
      end
    end
  end
end

app/controllers/mypage/purchase/closed_controller.rb
class Mypage::Purchase::ClosedController < ApplicationController
  # ログインしていない場合ログインページへ移動する
  before_action :authenticate_user!

  def index
    # 取引済みの購入情報を全て取得
    @deals = current_user.buyer_deals.closed().order(id: :desc).includes(:item)
  end
end

app/controllers/mypage/sale/closed_controller.rb
class Mypage::Sale::ClosedController < ApplicationController
  
  def index
    # 販売済みの情報を全て取得
    @deals = current_user.seller_deals.closed.order(id: :desc).includes(:item)
  end
end

app/controllers/mypage/sale/dealing_controller.rb
class Mypage::Sale::DealingController < ApplicationController
  # ログインしていない場合ログインページへ移動する
  before_action :authenticate_user!

  def index
    # 取引中の販売情報を全て取得
    @deals = current_user.seller_deals.in_progress.order(id: :desc).includes(:item)
  end
end

app/controllers/mypage/sale/selling_controller.rb
class Mypage::Sale::SellingController < ApplicationController
  # ログインしていない場合ログインページへ移動する
  before_action :authenticate_user!

  def index
    # 販売中の商品情報を取得
    @items = current_user.items.includes(:sales_state).user_selling()
  end
end

app/views/mypage/sale/closed/index.html.haml
= render 'joint/header'
= render 'users/user-breadcrumb', {symbol: :mypage_sale_closed_index}
.user-wrapper
  %main.user-main
    .user-container
      .h2.user-tab-headline
        出品した商品
      .user-tabcontent__tabbar
        = link_to mypage_sale_selling_index_path, class:"user-tabcontent__tabbar--link" do
          .user-tabcontent__tabbar__tab3
            出品中
        = link_to mypage_sale_dealing_index_path, class:"user-tabcontent__tabbar--link" do
          .user-tabcontent__tabbar__tab3
            取引中
        = link_to mypage_sale_closed_index_path, class:"user-tabcontent__tabbar--link" do
          .user-tabcontent__tabbar__tab3.user-tabcontent__tabbar__tab3--active
            売却済み
      .user-tabcontent__page
        - if @deals.count > 0
          %ul.user-notification
            -# 直近の販売済み商品を表示
            = render partial: "users/deal-sale-list-item", collection: @deals, as: "deal"
          -# Todo: 販売済み商品が一定数以上の時にページネーションが必要になるが現時点では非対応とした
        - else
          = render "users/nolist-item", { text: '売却済みの商品がありません' }
    -# ナビゲーションバー
    = render 'users/user-navigation'
= render 'joint/app__dl'
= render 'joint/footer'
= render 'joint/exhibit__button'