config/routes.rb
Rails.application.routes.draw do
  devise_for :users,controllers: {
    registrations: 'users/registrations',
    omniauth_callbacks: "users/omniauth_callbacks"
  } 
  devise_scope :user do
      get 'personal_name_google' => 'users/registrations#personal_name_google'
      get 'phone_number_google' => 'users/registrations#phone_number_google'
      get 'personal_name' => 'users/registrations#personal_name'
      get 'phone_number' => 'users/registrations#phone_number'
      get 'address' => 'users/registrations#address'
      get 'creditcard' => 'users/registrations#creditcard'
  end
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :joint,only:[:index]
  root to: 'joint#index'

  # マイページ
  resource :mypage, only:[:show] do
    member do
      # ログアウト画面の表示
      get :logout
    end
    scope module: :mypage do
      namespace :sale do
        resources :selling, only: [:index]
        resources :dealing, only: [:index]
        resources :closed, only: [:index]
      end
      namespace :purchase do
        resources :dealing, only: [:index]
        resources :closed, only: [:index]
      end
      resource :profiles, only:[:new, :create, :edit, :update]
      resource :personals, only:[:edit, :update]
      resources :mypage_payjp_cards, only:[:index, :new, :create, :destroy], path: "cards", as: :cards
    end
  end

  resources :users, only:[:show]

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?


  resources :items do

    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
      get 'get_deliver_method', defaults: { format: 'json' }
      get 'get_deliver_method_cash_on_delivery', defaults: { format: 'json' }
    end

    member do
      # 商品販売状態の変更
      patch :deactivate
      patch :activate
    end

    # 商品購入ページ
    scope module: :deals do
      resources :purchase, only: [:new, :create], path: 'transaction'
      resources :deals_payjp_cards, only: [:index, :new, :create], path: "transaction/cards", as: :purchase_card
      resources :deals_delivery_addresses, only: [:new, :create, :edit, :update], path: "transaction/delivery_addresses", as: :purchase_delivery_addresses
    end
  end

  namespace :api do
    resources :brands, only: [] do
      collection do
        # ブランドインクリメンタルサーチ
        get 'search', defaults: { format: 'json' }
      end
    end
  end
end

app/models/deal.rb
class Deal < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  #Validation
  validates :item, :payment, presence: true
  #Association
  has_one :item
  has_one :payment, dependent: :destroy
  belongs_to :buyer, class_name: 'User', foreign_key: 'buyer_id'
  belongs_to :seller, class_name: 'User', foreign_key: 'seller_id'
  belongs_to_active_hash :deal_state
  # scope
  # 直近の取引を取得
  scope :recent, -> (count) { order(id: :desc).limit(count) }
  # 取引中（状態が取引完了でない）の取引を取得
  scope :in_progress, -> { where.not(deal_state_id: 5) }
  # 取引済み（状態が取引完了）の取引を取得
  scope :closed, -> { where(deal_state_id: 5) }
end

app/controllers/deals/deals_delivery_addresses_controller.rb
class Deals::DealsDeliveryAddressesController < DeliveryAddressesController
  def new
    # 既に発送先が登録されているのにnewページを表示した時はeditページにリダイレクトする
    if current_user.delivery_address
      redirect_to edit_item_purchase_delivery_address_path(params[:item_id], current_user.delivery_address)
    else
      super
    end
  end

  def create
    # 入力情報とユーザー情報を元に配送先を保存
    @delivery_address = DeliveryAddress.new(address_params)
    @delivery_address.user = current_user
    if @delivery_address.save
      redirect_to(new_item_purchase_path, notice: "配送先を登録しました")
    else
      flash[:alert] = '入力内容に不備があります'
      render :new
    end
  end

  def update
    # 入力情報とを元に配送先を更新
    @delivery_address = DeliveryAddress.find(params[:id])
    if @delivery_address.user_id == current_user.id
      if @delivery_address.update(address_params)
        redirect_to(new_item_purchase_path, notice: "配送先を変更しました")
      else
        flash[:alert] = '入力内容に不備があります'
        render :edit
      end
    end
  end

private
  def address_params
    params.require(:delivery_address).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :zip_code, :prefecture_id, :city, :address, :building, :phone_number)
  end
end

app/controllers/deals/deals_payjp_cards_controller.rb
class Deals::DealsPayjpCardsController < PayjpCardsController
end

app/controllers/deals/purchase_controller.rb
class Deals::PurchaseController < ApplicationController

  # ログインしていない場合ログインページへ移動する
  before_action :authenticate_user!
  # APIキーを使ってPayjpクラスを初期化する
  before_action :set_api_key, only:[:create]
  # 購入確認商品を取得する
  before_action :get_item, only:[:new, :create]

  def new
    # 商品が出品中でないのにリクエストが来た時商品詳細ページへリダイレクト
    return redirect_to(item_path(@item), alert:"商品が出品中でないため購入できません") unless @item.sales_state_id == 1
    # ログインユーザーのカード情報を取得する
    @credit_card = current_user.credit_card
    @payjp_card = @credit_card&.getPayjpDefaultCard
  end

  def create
    # 商品が出品中でないのに購入リクエストが来た時商品詳細ページへリダイレクト
    return redirect_to(item_path(@item), alert:"商品が出品中でないため購入できません") unless @item.sales_state_id == 1
    # 自分の出品商品なのに購入リクエストが来た時商品詳細ページへリダイレクト
    return redirect_to(item_path(@item), alert:"自分が出品した商品は購入できません") if @item.seller == current_user
    #トランザクション開始
    ActiveRecord::Base.transaction do
      begin
        # 取引作成
        @deal = Deal.new(date: Time.now)
        @deal.item = @item
        @deal.buyer = current_user
        @deal.seller = @item.seller
        # 支払い金額の登録（現時点ではポイント管理機能がないためポイント支払いを０とする）
        @deal.build_payment(amount: @item.amount, point: 0)
        # 取引状態を配送待ちにして保存する
        @deal.deal_state_id = 2
        @deal.save!
        # 商品の販売状況を売り切れに変更
        @item.sales_state_id = 3
        @item.save!
        # ユーザーのpayjp顧客情報を取得
        customer = Payjp::Customer.retrieve(current_user.credit_card.customer_id)
        # デフォルトカードで支払いを行う
        charge = Payjp::Charge.create(
          :amount => @item.amount,
          :customer => customer.id,
          :currency => 'jpy',
        )
        # 支払い結果のエラーレスポンスを確認しエラー発生時は例外を発生
        if charge.respond_to? :error
          raise ActiveRecord::Rollback
        end
      rescue => error
        # 例外発生時は購入画面に戻りロールバックする
        flash.now[:alert] = '商品購入ができませんでした。申し訳ありませんがもう一度操作してください'
        render :new
        raise ActiveRecord::Rollback
      end
    end
  end

  private
  # PAY.JP APIの秘密鍵をセット
  def set_api_key
    require "payjp"
    Payjp.api_key = Rails.application.credentials.payjp[:api_key]
  end
  # 購入確認商品を取得する
  def get_item
    # 購入確認商品を取得する
    @item = Item.find(params[:item_id]).decorate
  end
end

app/controllers/mypage/purchase/closed_controller.rb
class Mypage::Purchase::ClosedController < ApplicationController
  # ログインしていない場合ログインページへ移動する
  before_action :authenticate_user!

  def index
    # 取引済みの購入情報を全て取得
    @deals = current_user.buyer_deals.closed().order(id: :desc).includes(:item)
  end
end

app/controllers/mypage/purchase/dealing_controller.rb
class Mypage::Purchase::DealingController < ApplicationController
  # ログインしていない場合ログインページへ移動する
  before_action :authenticate_user!

  def index
    # 取引中の購入情報を全て取得
    @deals = current_user.buyer_deals.in_progress.order(id: :desc).includes(:item)
  end
end

app/views/deals/purchase/check_item.html.haml
.deals-wrapper
  = render 'deals/header'
  %main.deals-main
    .deals-content
      %section.deals-content__section
        .deals-content__section__w320
          %h2.deals-content__section__w320__headline
            購入内容の確認
      %section.deals-content__section
        .deals-content__section__w320
          .deals-content__section__w320__order
            .deals-content__section__w320__order__item
              = image_tag 'item-sample.jpg', class: "deals-content__section__w320__order__item__image"
              %p.deals-content__section__w320__order__item__name
                【オススメ‼】チャンピオン プルオーバー パーカー 星条旗 ビックロゴ 総柄
              %p.deals-content__section__w320__order__item__cost
                %span.deals-content__section__w320__order__item__cost--price
                  ¥X,XXX
                %span.deals-content__section__w320__order__item__cost--deliverymethod
                  送料込み
            .deals-content__section__w320__order__point
              ポイントはありません
            .deals-content__section__w320__order__payment
              .deals-content__section__w320__order__payment__left
                支払い金額
              .deals-content__section__w320__order__payment__right
                ¥X,XXX
            .deals-content__section__w320__order__button
              購入する
      %section.deals-content__section
        .deals-content__section__w320
          .deals-content__section__w320__method
            %h3.deals-content__section__w320__method__headline
              配送先
            .deals-content__section__w320__method__content
              〒XXX-XXXX
              %br
              XX県 YYY市 ZZ町 1-2-3 ABCマンション101
              %br
              XX XX
            = link_to purchase_address_new_path, class: "deals-content__section__w320__method__change" do
              変更する
              = fa_icon 'angle-right lg', class: 'deals-content__section__w320__method__change__icon'
      %section.deals-content__section
        .deals-content__section__w320
          .deals-content__section__w320__method
            %h3.deals-content__section__w320__method__headline
              支払い方法
            - if @payjp_card
              = render 'payjp_cards/card', {payjp_card: @payjp_card}
              = link_to purchase_cards_path, class: "deals-content__section__w320__method__change" do
                変更する
                = fa_icon 'angle-right lg', class: 'deals-content__section__w320__method__change__icon'
            - else
              .deals-content__section__w320__method__content
                カードを登録してください
              = link_to purchase_cards_new_path, class: "deals-content__section__w320__method__change" do
                変更する
                = fa_icon 'angle-right lg', class: 'deals-content__section__w320__method__change__icon'
  = render 'deals/footer'

app/views/deals/purchase/create.html.haml
.deals-wrapper
  = render 'deals/header'
  %main.deals-main
    .deals-content
      .deals-content__section
        .deals-content__section__w320
          %h2.deals-content__section__w320__headline
            商品を購入しました
      .deals-content__section
        .deals-content__section__w320
          %p.deals-content__section__w320__notice
            = link_to root_path, class: "deals-content__section__w320__notice--link" do
              トップページへ戻る
  = render 'deals/footer'

app/views/deals/purchase/new.html.haml
.deals-wrapper
  = render 'deals/header'
  %main.deals-main
    = form_with model: @item, local: true, url: item_purchase_index_path, method: :post, id: 'deal_form' do |f|
      .deals-content
        .deals-content__section
          .deals-content__section__w320
            %h2.deals-content__section__w320__headline
              購入内容の確認
        .deals-content__section
          .deals-content__section__w320
            .deals-content__section__w320__order
              .deals-content__section__w320__order__item
                = image_tag @item.item_images.first.image.url, class: "deals-content__section__w320__order__item__image"
                %p.deals-content__section__w320__order__item__name
                  = @item.name
                %p.deals-content__section__w320__order__item__cost
                  %span.deals-content__section__w320__order__item__cost--price
                    = @item.amount_text
                  %span.deals-content__section__w320__order__item__cost--deliverymethod
                    = @item.cash_on_delevery_text
              .deals-content__section__w320__order__point
                ポイントはありません
              .deals-content__section__w320__order__payment
                .deals-content__section__w320__order__payment__left
                  支払い金額
                .deals-content__section__w320__order__payment__right
                  = @item.amount_text
              -if current_user&.can_purchase? && @item.seller != current_user
                = f.submit "購入する", data: {confirm: "商品を購入します。よろしいですか？"}, class: "deals-content__section__w320__order__button--enable"
              - else
                .validation-error__text
                  - if @item.seller == current_user
                    出品した商品は購入できません
                  - else
                    配送先と支払い方法の入力を完了してください。
                .deals-content__section__w320__order__button--disenable
                  購入する
        .deals-content__section
          .deals-content__section__w320
            .deals-content__section__w320__method
              %h3.deals-content__section__w320__method__headline
                配送先
              .deals-content__section__w320__method__content
                - if current_user&.delivery_address
                  = "〒#{current_user.delivery_address.zip_code}"
                  %br
                  = current_user.delivery_address.decorate.full_address
                  %br
                  = current_user.delivery_address.decorate.full_name
                - else
                  配送先を登録してください
              = link_to current_user.delivery_address ? edit_item_purchase_delivery_address_path(@item, current_user.delivery_address) : new_item_purchase_delivery_address_path, class: "deals-content__section__w320__method__change" do
                変更する
                = fa_icon 'angle-right lg', class: 'deals-content__section__w320__method__change__icon'
        .deals-content__section
          .deals-content__section__w320
            .deals-content__section__w320__method
              %h3.deals-content__section__w320__method__headline
                支払い方法
              - if @payjp_card
                = render 'payjp_cards/card', {payjp_card: @payjp_card}
                = link_to item_purchase_card_index_path, class: "deals-content__section__w320__method__change", data: {"turbolinks": false} do
                  変更する
                  = fa_icon 'angle-right lg', class: 'deals-content__section__w320__method__change__icon'
              - else
                .deals-content__section__w320__method__content
                  カードを登録してください
                = link_to new_item_purchase_card_path, class: "deals-content__section__w320__method__change", data: {"turbolinks": false} do
                  変更する
                  = fa_icon 'angle-right lg', class: 'deals-content__section__w320__method__change__icon'
  = render 'deals/footer'